/**
 * Cross-implementation validation: the TypeScript port and the Python
 * reference must produce IDENTICAL projections of the same persisted log.
 *
 * data/genesis-projection.golden.json is generated by the Python oracle:
 *   python3 scripts/validate-trace.py --json > data/genesis-projection.golden.json
 * The trace it projects is the genesis trace — the recorded decisions of this
 * repository's own construction — so this test is simultaneously the
 * dual-implementation check AND the empirical ontology validation that
 * MEMORY_MODEL §8 names as the open risk.
 */

import { readFileSync } from "node:fs";
import { expect, test } from "vitest";
import {
  authoritativeFingerprint,
  loadLog,
  projectTessera,
  serializeLog,
} from "../src/index.js";

const traceUrl = new URL("../../data/genesis-trace.jsonl", import.meta.url);
const goldenUrl = new URL("../../data/genesis-projection.golden.json", import.meta.url);

function loadGenesis() {
  const records = readFileSync(traceUrl, "utf8")
    .split("\n")
    .filter((l) => l.trim().length > 0)
    .map((l) => JSON.parse(l) as unknown);
  return loadLog(records);
}

test("genesis trace loads clean through every TS guard", () => {
  const log = loadGenesis();
  expect(log.head).toBeGreaterThanOrEqual(10);
});

test("TS projection is byte-identical to the Python oracle's", () => {
  const log = loadGenesis();
  const ours = projectTessera(log);
  const golden = JSON.parse(readFileSync(goldenUrl, "utf8")) as unknown;
  // Compare via canonical JSON (sorted keys) — same normalization the oracle used.
  expect(canonical(ours)).toEqual(canonical(golden));
});

test("genesis trace survives a full TS replay round-trip (I4)", () => {
  const log = loadGenesis();
  const live = projectTessera(log);
  const reloaded = loadLog(JSON.parse(JSON.stringify(serializeLog(log))));
  expect(authoritativeFingerprint(projectTessera(reloaded))).toEqual(
    authoritativeFingerprint(live),
  );
});

/** Recursively sort object keys so key order can never mask/introduce a diff. */
function canonical(x: unknown): unknown {
  if (Array.isArray(x)) return x.map(canonical);
  if (typeof x === "object" && x !== null) {
    return Object.fromEntries(
      Object.entries(x as Record<string, unknown>)
        .sort(([a], [b]) => (a < b ? -1 : a > b ? 1 : 0))
        .map(([k, v]) => [k, canonical(v)]),
    );
  }
  return x;
}
