"""
test_canonical.py — RFC 8785 canonical bytes + the record hash chain (ADR-003 §5, §8).

The golden is generated by this same module, so reproducing it here proves
only that it is current. The cross-implementation proof is the TypeScript
side reproducing the identical file (core/test/canonical.test.ts). The tests
below also pin properties the golden can't show on its own.

Run:  python3 test_canonical.py
"""

import json
from pathlib import Path

from canonical import CanonicalError, GENESIS_DIGEST, canonicalize, chain_digest, log_digest
from tessera_projection import load_log

ROOT = Path(__file__).resolve().parent.parent
GOLDEN = json.loads((ROOT / "data" / "canonical.golden.json").read_text())


def _trace(name):
    return [json.loads(l) for l in (ROOT / "data" / name).read_text().splitlines() if l.strip()]


def _refused(v) -> bool:
    try:
        canonicalize(v)
    except CanonicalError:
        return True
    return False


def test_golden_cases_reproduce():
    for c in GOLDEN["cases"]:
        assert canonicalize(c["value"]) == c["canonical"], c["name"]


def test_golden_genesis_digest_is_current():
    assert list(GOLDEN["traces"]) == ["genesis-trace.jsonl"]
    for name, want in GOLDEN["traces"].items():
        assert log_digest(load_log(_trace(name))) == want["head_digest"], name


def test_fail_closed_refusals():
    for r in GOLDEN["refused"]:
        assert _refused(r["value"]), r["name"]
    assert _refused(float("nan")) and _refused([float("inf")])
    assert _refused("\ud800") and _refused({"\udc00": 1})
    assert _refused({1: "non-string key"}) and _refused(object())


def test_chain_detects_edit_delete_reorder():
    recs = _trace("genesis-trace.jsonl")
    head = chain_digest(recs)
    assert chain_digest(recs[:-1]) != head
    assert chain_digest([recs[1], recs[0], *recs[2:]]) != head
    assert chain_digest([{**recs[0], "agent_id": "forged"}, *recs[1:]]) != head
    assert chain_digest([]) == GENESIS_DIGEST


def test_key_order_is_utf16_not_codepoint():
    # By code point U+FFFF < U+1F600; by UTF-16 code units the astral char's
    # high surrogate 0xD83D < 0xFFFF. The orders disagree for BMP chars above
    # the surrogate block — pin RFC 8785's choice (code units: astral first).
    s = canonicalize({"￿": 1, "\U0001F600": 2})
    assert s.index("\U0001F600") < s.index("￿")


if __name__ == "__main__":
    tests = [v for k, v in sorted(globals().items()) if k.startswith("test_")]
    for t in tests:
        t()
        print(f"  ok  {t.__name__}")
    print(f"\n{len(tests)}/{len(tests)} canonical-bytes properties hold.")
