#!/usr/bin/env python3
"""Render data/canonical.golden.json from the reference (ADR-003 §5, §8).

RFC 8785 cases, refusal cases, and the chain head digest of the genesis
fixture trace. core/test/canonical.test.ts and reference/test_canonical.py both
reproduce every value byte-for-byte. Never hand-edit the output:

  python3 scripts/render-canonical-golden.py >| data/canonical.golden.json
"""

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "reference"))

from canonical import CanonicalError, canonicalize, log_digest  # noqa: E402
from tessera_projection import load_log  # noqa: E402

CASES = [
    ("key order by UTF-16 code units",
     {"b": 1, "a": 2, "\u00e9": 3, "\U0001F600": 4, "\uffff": 5, "a\u0000": 6}),
    ("string escapes", ["x\u2028\u0007\"\\\u00e9\U0001F600\t\n\r\b\f\u001f\u007f"]),
    ("numbers", [0, -0.0, 1.0, 0.7, 1e15, 1e-7, 1e-6, 123e-20, 1.5e-300, 5e-324,
                 0.1 + 0.2, -0.000001, 9007199254740991, 4.35, 1 / 3, 1.23456e-5, 2.5e-7]),
    ("large magnitudes are IEEE doubles, not refusals (touchstone P1)",
     [1e21, 1.5e300, 9007199254740993, 1730000000000000000, -1e16, 2**64]),
    ("nesting and literals", {"z": {"y": [True, False, None, [], {}]}, "a": ""}),
    ("an event record", {
        "id": "tp-001", "type": "decision", "agent_id": "claude", "schema_version": 1,
        "birth_status": "pending_evidence",
        "claim": {"narrative": "n", "shadow": {"certainty": 0.9, "tag": "TRACE"}},
        "evidence": [{"kind": "test_exit", "ref": "npm test", "checked_at": None, "signer": None}],
        "targets": [], "is_trust_root": False, "timestamp": None}),
]

# Refused by both implementations (fail-closed). JSON can't carry NaN or a
# lone surrogate portably, so those are tested in code, not here.
REFUSED: list = []  # nothing JSON-representable is refused; see the tests for NaN/surrogates


def main() -> int:
    cases = [{"name": n, "value": v, "canonical": canonicalize(v)} for n, v in CASES]
    refused = []
    for n, v in REFUSED:
        try:
            canonicalize(v)
        except CanonicalError:
            refused.append({"name": n, "value": v})
            continue
        raise SystemExit(f"refusal case {n!r} was accepted")
    # Only the genesis fixture is pinned: it changes deliberately, with the
    # projection golden. Live traces are cross-checked at test time instead
    # (canonical.test.ts asks the oracle), so appending an event needs no regen.
    traces = {}
    for t in [ROOT / "data" / "genesis-trace.jsonl"]:
        recs = [json.loads(line) for line in t.read_text().splitlines() if line.strip()]
        traces[t.name] = {"events": len(recs), "head_digest": log_digest(load_log(recs))}
    print(json.dumps({
        "_note": "Generated by scripts/render-canonical-golden.py — do not hand-edit.",
        "cases": cases, "refused": refused, "traces": traces,
    }, indent=2, ensure_ascii=False))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
